---
name: test

on:
  pull_request:
    branches:
    - main

  push:
    branches:
    - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Setup Go environment
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        go-version-file: acceptance/go.mod
        cache: true
        cache-dependency-path: acceptance/go.sum

    - name: Install shellspec
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#homebrew-note
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew tap shellspec/shellspec
        brew install shellspec

    - name: Run checks
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        make test
